### ISSUE TITLE
Failed to record video 

### ISSUE THREAD

**Issue by Shri-Harini-Ramesh-99** [MobileRoboticsSkoltech/OpenCamera-Sensors#73]
While recording video with IMU recording, the error message "Failed to record video" appears on the screen. What causes this to happen?

**Comment by licaon-kter** [comment]
On my Android AOSP11, 3 back camera setup
```
E CHIUSECASE: [ERROR  ] chxextensionmodule.cpp:2579 InitializeOverrideSession() For cameraId = 0 CreateUsecaseObject failed
E CamX    : [ERROR][HAL    ] camxhaldevice.cpp:897 ConfigureStreams() CHI Module failed to configure streams
E Camera3-Device: Camera 0: configureStreamsLocked: Unable to configure streams with HAL: Function not implemented (-38)
W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
D CameraTraces: Process trace saved. Use dumpsys media.camera to view.
E CameraDeviceClient: endConfigure: Camera 0: Error configuring streams: Function not implemented (-38)
E CameraCaptureSession: Session 1: Failed to create capture session; configuration failed
E CameraController2: CameraAccessException trying to create capture session
E CameraController2: reason: 3
E CameraController2: message: CAMERA_ERROR (3): endConfigure:518: Camera 0: Error configuring streams: Function not implemented (-38)
W System.err: android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): endConfigure:518: Camera 0: Error configuring streams: Function not implemented (-38)
D CameraController2: onConfigureFailed: android.hardware.camera2.impl.CameraCaptureSessionImpl@cb3b156
D CameraController2: captureSession was: null
W System.err:    at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1012)
W System.err:    at android.hardware.camera2.impl.ICameraDeviceUserWrapper.endConfigure(ICameraDeviceUserWrapper.java:119)
W System.err:    at android.hardware.camera2.impl.CameraDeviceImpl.configureStreamsChecked(CameraDeviceImpl.java:496)
W System.err:    at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:691)
W System.err:    at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:539)
W System.err:    at net.sourceforge.opencamera.cameracontroller.CameraController2.createCaptureSession(CameraController2.java:5422)
W System.err:    at net.sourceforge.opencamera.cameracontroller.CameraController2.initVideoRecorderPostPrepare(CameraController2.java:7318)
W System.err:    at net.sourceforge.opencamera.preview.Preview.prepareVideoRecording(Preview.java:5635)
W System.err:    at net.sourceforge.opencamera.preview.Preview.takePicture(Preview.java:5391)
W System.err:    at net.sourceforge.opencamera.preview.Preview.takePicturePressed(Preview.java:5091)
W System.err:    at net.sourceforge.opencamera.MainActivity.takePicturePressed(MainActivity.java:4512)
W System.err:    at net.sourceforge.opencamera.MainActivity.takePicture(MainActivity.java:4489)
W System.err:    at net.sourceforge.opencamera.MainActivity.clickedTakePhoto(MainActivity.java:1661)
W System.err:    at java.lang.reflect.Method.invoke(Native Method)
W System.err:    at android.view.View$DeclaredOnClickListener.onClick(View.java:6263)
W System.err:    at android.view.View.performClick(View.java:7448)
W System.err:    at android.view.View.performClickInternal(View.java:7425)
W System.err:    at android.view.View.access$3600(View.java:810)
W System.err:    at android.view.View$PerformClick.run(View.java:28309)
W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
W System.err:    at android.os.Looper.loop(Looper.java:223)
W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7705)
W System.err:    at java.lang.reflect.Method.invoke(Native Method)
W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
W System.err: Caused by: android.os.ServiceSpecificException: endConfigure:518: Camera 0: Error configuring streams: Function not implemented (-38) (code 10)
W System.err:    at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
W System.err:    at android.os.Parcel.createException(Parcel.java:2357)
W System.err:    at android.os.Parcel.readException(Parcel.java:2340)
W System.err:    at android.os.Parcel.readException(Parcel.java:2282)
W System.err:    at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.endConfigure(ICameraDeviceUser.java:799)
W System.err:    at android.hardware.camera2.impl.ICameraDeviceUserWrapper.endConfigure(ICameraDeviceUserWrapper.java:116)
W System.err:    ... 24 more
E Preview : camera exception starting video recorder
W System.err: net.sourceforge.opencamera.cameracontroller.CameraControllerException
W System.err:    at net.sourceforge.opencamera.cameracontroller.CameraController2.createCaptureSession(CameraController2.java:5474)
W System.err:    at net.sourceforge.opencamera.cameracontroller.CameraController2.initVideoRecorderPostPrepare(CameraController2.java:7318)
W System.err:    at net.sourceforge.opencamera.preview.Preview.prepareVideoRecording(Preview.java:5635)
W System.err:    at net.sourceforge.opencamera.preview.Preview.takePicture(Preview.java:5391)
W System.err:    at net.sourceforge.opencamera.preview.Preview.takePicturePressed(Preview.java:5091)
W System.err:    at net.sourceforge.opencamera.MainActivity.takePicturePressed(MainActivity.java:4512)
W System.err:    at net.sourceforge.opencamera.MainActivity.takePicture(MainActivity.java:4489)
W System.err:    at net.sourceforge.opencamera.MainActivity.clickedTakePhoto(MainActivity.java:1661)
W System.err:    at java.lang.reflect.Method.invoke(Native Method)
W System.err:    at android.view.View$DeclaredOnClickListener.onClick(View.java:6263)
W System.err:    at android.view.View.performClick(View.java:7448)
W System.err:    at android.view.View.performClickInternal(View.java:7425)
W System.err:    at android.view.View.access$3600(View.java:810)
W System.err:    at android.view.View$PerformClick.run(View.java:28309)
W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
W System.err:    at android.os.Looper.loop(Looper.java:223)
W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7705)
W System.err:    at java.lang.reflect.Method.invoke(Native Method)
W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

Note that latest OpenCamera records video just fine.
